### PR TITLE
Github Actions - expand test matrix

### PR DESCRIPTION
**Pull request by asedeno**
Fixes: #207

Adding Python 3.7, 3.8, 3.9.
Adding Django 3.1, 3.2.

Reworking coveralls upload to handle parallel jobs with notification of completion.

### CODE REVIEW

**Comment by claudep** [comment]
Looks great, thanks!
Now I know this is the traditional way of doing this. However in the spirit of greener practices, what would you think about testing only the minimal and maximal Python versions (3.6, 3.9) instead of the whole range?

**Comment by asedeno** [comment]
I think that would be fine. It is easy enough to change again in the future if we find we need additional test coverage.

**Comment by asedeno** [comment]
I've rebased this, and got rid of the python3-slim container for the final coveralls task. ubuntu-latest has all the python3 we need, so container setup was wasteful.

**Comment by claudep** [comment]
:+1:

**Pull request merged**
