### PR TITLE
Replace Travis CI by GitHub Actions

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
I'm currently struggling to find the correct paths to copy files between django-haystack and xapian-haystack checkouts.

**Comment by claudep** [comment]
Now I'm blocked on how to use the system python3-xapian when running any python command...

**Comment by claudep** [comment]
I was finally able to set PYTHONPATH, but the system-installed python3-xapian is version specific, so it cannot be used with different Python versions. Looks like we have no other choice than building xapian in each test run, which is resource wasting IMHO.

**Comment by asedeno** [comment]
Using #201 and `actions/cache@v2` to cache the wheel, you'll have a better time.

```
- name: Check for cached xapian wheel
  id: xapian-cache
  uses: actions/cache@v2
  with:
    path: xapian*.whl
    key: xapian-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('xapian_wheel_builder.sh') }}
- name: Build xapian wheel
  if: steps.xapian-cache.outputs.cache-hit != 'true'
  run: |
    ./xapian_wheel_builder.sh
```

This leads to a cache key that looks something like this:
`xapian-Linux-/opt/hostedtoolcache/Python/3.6.14/x64-3102be70278fa7f0245c13c9aadfdd7c6caa11774c7374646652f70378e2887b`

Once you've built or pulled the wheel from cache, install as you would any wheel.

**Comment by claudep** [comment]
@asedeno, Now that #201 is in, do you want/have time to take this patch and finish it with the cached wheels?

**Comment by asedeno** [comment]
@claudep, I've got something going on my fork, but the wheel builder does not bring along a `xapian-delve` so the tests fail. I'll try to look into that.

**Comment by claudep** [comment]
I'd be grateful!

**Comment by asedeno** [comment]
@claudep, here's what I have cooking:

- A `-t` flag to `xapian_wheel_builder.sh` will package the build's `xapian-delve` along side the library and bindings.
- `tests/xapian_tests/tests/test_backend.py` will learn to look for a `xapian-delve` in the same path as the `xapian` module, and if it finds one, it will use it.

**Pull request merged**
