### PR TITLE
Fix PY2 error

### PR DESCRIPTION
**Pull request by karolyi**
Last year I committed a change, which went red because of PY2 incompatibility. I hereby fix it, please merge ASAP.

### CODE REVIEW

**Comment by karolyi** [comment]
@jorgecarleitao, are you still maintaining this project? I have some improvements, if you add me as a committer to this project, I'll add them.

**Comment by notanumber** [comment]
Hey @karolyi  Thanks for the pull requests. I haven't been the maintainer for this project for several years but if we don't hear from @jorgecarleitao within the next few days I'll go ahead and add you as a contributor.

**Comment by karolyi** [comment]
@notanumber thx, I'm working with xapian in one of my projects and I had to take a deep dive down the code. I have a lot updates, which will help it out in the long run.

**Comment by jorgecarleitao** [comment]
Hi @karolyi. Sorry for the delay, hadn't had much time for looking at it. Just reviewed and pushed your two changes to master. Thanks a lot for them!!!

I haven't bumped the version because the build is failing for Django 1.8. This is a blocker for releasing a new version.

**Comment by karolyi** [comment]
I intend to fix that, and I have a couple of additions (stopwords, parameterizable weighing algorithms) too. If I you can add me as a contributor, we can pick up some speed too.

**Comment by jorgecarleitao** [comment]
I am very happy to know that you have a lot of fixes. Could you PR them? I will gladly review them.

**Comment by claudep** [comment]
Most of the proposed changes have been merged with other pull requests. If you still find some things remaining to improve, please rebase or propose a new pull request.

**Pull request closed without merging**
