### PR TITLE
Test against multiple Django versions

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
I was just working on that so I could merge your other PR, thanks claudep.

**Comment by claudep** [comment]
Tests are failing with 1.7/1.8, as expected! I think this should not prevent us from pushing the patch.

**Comment by jorgecarleitao** [comment]
I'm not sure @claudep: I pulled your PR, updated to Django 1.8 and pulled django-haystack@master to a virtualenv in my local machine. Running the tests stalled my terminal, which was what also happened in Travis. I think it is something else.

**Comment by claudep** [comment]
This patch only shows that there are issues with 1.7/1.8. It doesn't introduce them :-) Then, other patches will try to fix them, I'll gladly take the time to help with that.

**Comment by jorgecarleitao** [comment]
Good point. I hadn't though it that way. Merged. Thank you for the patch. I'm very glad you contributed to xapian-haystack :-)

**Comment by claudep** [comment]
There is a circular dependency issue when running tests with Django > 1.6. Running django-admin.py is calling django.setup(), but then, during `haystack` initialization, test_haystack/__init__.py is also loaded and does a new django.setup(), which deadlocks...

**Comment by claudep** [comment]
I'm sorry, but I don't see how we can circumvent this issue currently. Maybe ask haystack to move this `setup()` elsewhere? Feel free to revert this commit, until that deadlock issue is resolved.

**Pull request merged**
