### PR TITLE
Restore compatibility with latest django-haystack

### PR DESCRIPTION
**Pull request by claudep**
Please double-check the second commit of this series.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks a lot for this @claudep. I haven't forgotten. I am trying to fix the test problem in Python 3.

**Comment by claudep** [comment]
Yes, would be great if you could sort the xapian 4/python 3 install issue!

**Comment by jorgecarleitao** [comment]
This has been merged to master as I was able to fix the Python 3 install issue. Essentially, during installation, we were running Python while we were in a removed directory. This was an issue in Python 3 ([Python issue 22834](http://bugs.python.org/issue22834)). The fix was to `cd` to another directory before running Python.

This fixed all issues for upgrading for Xapian 1.4.1 and therefore Xapian-Haystack now supports Xapian 1.4.1. Thanks again for the help @claudep.

**Comment by claudep** [comment]
Thanks for merging and for solving the remaining issue!

**Pull request merged**
