### PR TITLE
install_xapian.sh: pin sphinx to avoid compatibility issues with 2.0

### PR DESCRIPTION
**Pull request by asedeno**
This should fix the build for now.

### CODE REVIEW

**Comment by HoshiYamazaki** [comment]
This solves issue described here:
https://github.com/notanumber/xapian-haystack/issues/188

So if you can't build it, do fork and do this one-liner for your project until this is merged into master.

**Comment by apavlo** [comment]
This fixes my problems. Thanks!

**Comment by claudep** [comment]
Thanks, committed in 0d8895b8cc. If you find a way to support sphinx>=2, would be great.

**Comment by asedeno** [comment]
> Thanks, committed in [0d8895b](https://github.com/notanumber/xapian-haystack/commit/0d8895b8cc93209437f8edeb2e9dca1c23304169). If you find a way to support sphinx>=2, would be great.

This is an issue in xapian itself, though it appears there has been some activity there after a long downtime, and perhaps sphinx>=2 works with xapain>=1.4.12?

**Pull request closed without merging**
