### PR TITLE
Remove force_text usage

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@asedeno do you have any idea why the tests fails soon with the django settings not configured error? I don't think the change of this patch can cause this error.

Sorry, I unintentionally pushed the commit to master.

**Comment by asedeno** [comment]
@claudep I do not know why, but I'll take a stab at it.

**Comment by asedeno** [comment]
Works with coverage 5.5, breaks with coverage 6.x, which provides an easy workaround for now, but I'd like to not pin coverage long term. Still digging.

**Comment by asedeno** [comment]
As far as I can tell, coverage 6.0+ is importing things early while figuring out what it should be tracing. This causes an early import of `haystack` which causes an early import of `haystack.constants` which is full of code that depends on django settings having been initialized, but that has not happed yet because it is too early.

Coverage docs have recently gained a note:

> _Modules named as sources may be imported twice, once by coverage.py to find their location, then again by your own code or test suite. Usually this isn’t a problem, but could cause trouble if a module has side-effects at import time._

In our .coveragerc file, we have in the sources list, `haystack.backends.xapian_backend`, which is causing `haystack` to be imported as per this note.

Our best bet is to pin coverage to 5.5 for now.

**Comment by asedeno** [comment]
Fixed in #213.

**Pull request closed without merging**
