### PR TITLE
Added commit argument to remove

### PR DESCRIPTION
**Pull request by alexole**

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Merged in a3a3a4e7cfba3e2e1be3a42abf59edd29ea03c05. Thank you @alexole.

**Comment by alexole** [comment]
But this is not about "update", this is about "remove".

**Comment by jorgecarleitao** [comment]
Sorry, it is 6756b685f17d5f8d1c0b858a81c6b6f9e4fa7bdf, not the one I mentioned. I forgot to push upstream your merge.

**Comment by alexole** [comment]
@jorgecarleitao thanks

**Pull request closed without merging**
